export const GET_LESSON = 'GET_LESSON';
export const UNMOUNT_LESSON = 'UNMOUNT_LESSON';
export const GET_SLIDE = 'GET_SLIDE';
export const GET_SLIDE_INDEX = 'GET_SLIDE_INDEX';
export const ADD_EMOTION = 'ADD_EMOTION';
export const GET_DISPLAYOBJECT = 'GET_DISPLAYOBJECT '
